### ISSUE TITLE
Vertical scroller 

### ISSUE THREAD

**Issue by Isi88** [GavickPro/News-Show-Pro-GK5#243]
Hello guys,

on my site with joomla 2.5, i used NSP GK4 with the vertical scroller.

At the moment I update my site to joomla 3. THe problem ist, i need a vertical scroll but NSP GK4 dosnt run on joomla 3 and gk5 has no vertical scroll.

What can i do?

Thank you for your answer!

many regards!

**Comment by ckubs** [comment]
@dziudek Hello. I had the same problem, with Joomla 3.3 and GK NSP. Everything worked as it should,  added a few NSP modules on the main page, customised something here and there. Today published and article, opened a NSP module and saved it to update something and suddenly I got the same type of error untill I disabled all of them. A few hours ago enabled Joomla system cache but I don't know if it has any connection with this.

**Comment by ckubs** [comment]
my error is targeting tag related tables _contentitem_tag_map _tags ..etc

**Comment by dziudek** [comment]
@ckubs - please provide a version of the module and full error.

**Comment by ckubs** [comment]
@dziudek Fixed my problem, sort of. First of all I resaved all my GK NSP modules and after that the error was gone, but I didn't got any articles displayed. Even though when I made the site, I imported all my old articles from wordpress in one category, and that category worked with your module. 

Fixed that one too with a little info discovered in Gavick forum.
I had a server time offset of six hours, as I'm in Romania and my site is hosted at Hostgator. Didn't know about that one since my new published articles had the right time on them.

**Comment by ANDiTKO** [comment]
Hello, re-saving, clearing browser and joomla cache, cheking if items exist and other things i tried did not help in my case. 

**Here is how i fixed it:**
Go to your module -> Basic Settings -> and Load the original.json configuration. Then re-save your module.

Seems like after updating the GKNews module the configuration format was changed.
