### ISSUE TITLE
url

### ISSUE THREAD

**Issue by KurtRe** [GavickPro/News-Show-Pro-GK5#277]
Hello, i am the webmaster of a schoolhomepage called www.jbhrs.de I use NSPGk5 for the first time. I have a problem with the url by all articls. The url is e.g.  http://www.jbhrs.de/index.php/aktuelles1/390-lerngang-zum-bestattungsunternehmen-hiller, but it must be http://www.jbhrs.de/index.php/lerngang-zum-bestattungsunternehmen-hiller witout "aktuelles1" (I Think this is the category) and without "390-" (I think this is the id of the article). The article is not shown in correct way In the first url. Perhaps you can help me. Sorry for my bad English.

**Comment by dziudek** [comment]
Hello,

It must be an issue with your configuration, because the NSP GK5 module uses a Joomla! helpers for generating the article URLs - so it is doing it like Joomla. Please make sure that you are using the latest version, please also try to rebuild your menu using the "Re-built menu" button in the menu manager.
