### ISSUE TITLE
Arrow

### ISSUE THREAD

**Issue by ChuJung** [GavickPro/News-Show-Pro-GK5#309]
Module mode - TechNews - Header I.
No icon for button "read more". Only text "arrow_forward"
`<i class="micon">arrow_forward</i>`
![dd2](https://cloud.githubusercontent.com/assets/14818398/10069775/f5f4bb5e-62b6-11e5-88e9-f3c8f458b6f0.jpg)
How can i fix it?

**Comment by dziudek** [comment]
Hello,

Please make sure that your template loads Material Design icons - if not - please override the portal mode output in that place

**Comment by ChuJung** [comment]
Thank you for answer. Can you tell how i can override the portal mode output? I'm noob in joomla, sorry.

**Comment by ChuJung** [comment]
And how can i center title of module?

**Comment by dziudek** [comment]
You have to copy this file and modify the marked line: https://github.com/GavickPro/News-Show-Pro-GK5/blob/J!3.0_compatible/mod_news_pro_gk5/tmpl/portal_modes/technews_header1/controller.php#L56 to **html/mod_news_pro_gk5/portal_modes/technews_header1/controller.php** file

In order to center the title - please try to add text-align: center for the **.gkTitle** selector

**Comment by alexantony2** [comment]
HI, i have the same issue <i class="micon">arrow_forward</i> as in the picture above, any solution? i am using purity III template on latest version of joomla, thanks
